- hosts: localhost
  become: true
  tasks:
  - name: install packages
    pacman:
      name:
        - git
        - neovim
        - tmux
        - fzf
        - fish
        - man
        - qtile
        - lightdm-gtk-greeter
  - name: change default shell
    shell: chsh -s `which fish`
